import React, {useEffect, useRef, useState} from 'react';
import {useRecorder} from './useRecorder.js';

const fmt = (seconds) => (seconds == null ? '—' : `${seconds.toFixed(1)}s`);

const fmtElapsed = (ms) => {
  const total = Math.floor(ms / 1000);
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
};

const TTS_CUES = [
  {
    group: 'Pause',
    items: [
      {label: 'Short', value: '، ', title: 'Short natural pause. Hamsa docs recommend punctuation for natural pauses.'},
      {label: 'Stop', value: '. ', title: 'Sentence stop with a clearer pause.'},
      {label: 'Long', value: '... ', title: 'Longer emphasis pause. Captions strip long dot runs later.'},
      {label: 'Paragraph', value: '\n\n', title: 'Break long text into shorter paragraphs for clearer pacing.'}
    ]
  },
  {
    group: 'Emotion',
    items: [
      {label: 'Urgent', value: '! ', title: 'Adds stronger emphasis through punctuation.'},
      {label: 'Question', value: '؟ ', title: 'Question intonation cue.'},
      {label: 'Concern', value: '😟 ', title: 'Supported emojis can affect voice delivery in Hamsa Media.'},
      {label: 'Warm', value: '🙂 ', title: 'Supported emojis can affect voice delivery in Hamsa Media.'}
    ]
  },
  {
    group: 'Natural',
    items: [
      {label: 'Umm', value: ' أممم، ', title: 'Natural filler; Hamsa docs list fillers for realism.'},
      {label: 'Uh', value: ' آه، ', title: 'Natural filler; useful before a careful turn.'}
    ]
  }
];

const insertAtSelectionStart = (text, selectionStart, cue) => {
  const start = Math.max(0, selectionStart ?? text.length);
  return `${text.slice(0, start)}${cue}${text.slice(start)}`;
};

const paceSelection = (text, selectionStart, selectionEnd, mode) => {
  const start = Math.max(0, selectionStart ?? text.length);
  const end = Math.max(start, selectionEnd ?? start);
  const selected = text.slice(start, end);
  if (!selected) return text;
  const replacement =
    mode === 'faster'
      ? selected.replace(/\s*[،,]\s*/g, ' ').replace(/\s*\.\.\.+\s*/g, ' ').replace(/\n{2,}/g, ' ')
      : selected.replace(/\s*[،,]\s*/g, '، ').replace(/([.؟!])\s+/g, '$1 ... ');
  return `${text.slice(0, start)}${replacement}${text.slice(end)}`;
};

function RegenBadge({regen}) {
  if (!regen) return null;
  if (regen.verdict === 'failed') return <span className="badge badge-failed">regen failed</span>;
  if (regen.verdict === 'longer')
    return (
      <span className="badge badge-stale" title="New WAV is longer than the old one — re-render the muted video before muxing.">
        longer — re-render needed
      </span>
    );
  if (regen.verdict === 'ok')
    return (
      <span className="badge badge-done" title="Same length or shorter — re-running the mux is enough.">
        updated — re-mux ok
      </span>
    );
  if (regen.verdict === 'new') return <span className="badge badge-done">generated</span>;
  return null;
}

function SourceTag({source}) {
  if (source === 'recorded') return <span className="badge badge-source" title="This scene's WAV is a recorded human take.">recorded</span>;
  return <span className="badge badge-source muted" title="This scene's WAV was generated by Hamsa AI.">AI</span>;
}

// Inline record control: Record → recording (elapsed + Stop) → preview + Save/Re-record/Cancel.
function RecordControl({entry, busy, dirty, onRecord}) {
  const rec = useRecorder();
  const [saving, setSaving] = useState(false);

  const save = async () => {
    if (!rec.blob) return;
    setSaving(true);
    try {
      await onRecord(entry.sceneId, rec.blob, rec.mimeType);
      rec.reset();
    } finally {
      setSaving(false);
    }
  };

  if (rec.state === 'recording' || rec.state === 'requesting') {
    return (
      <span className="record-control recording">
        <span className="rec-dot" /> <span className="mono">{fmtElapsed(rec.elapsedMs)}</span>
        <button className="btn" disabled={rec.state === 'requesting'} onClick={rec.stop}>
          Stop
        </button>
      </span>
    );
  }

  if (rec.state === 'recorded') {
    return (
      <span className="record-control review">
        <audio controls preload="auto" src={rec.url} />
        <button className="btn primary" disabled={saving || busy} onClick={save}>
          {saving ? 'Saving…' : 'Save take'}
        </button>
        <button className="btn" disabled={saving} onClick={rec.start}>
          Re-record
        </button>
        <button className="btn ghost" disabled={saving} onClick={rec.reset}>
          Cancel
        </button>
      </span>
    );
  }

  return (
    <span className="record-control">
      <button
        className="btn"
        disabled={busy || dirty}
        title={dirty ? 'Save the text first' : 'Record your own narration for this scene'}
        onClick={rec.start}
      >
        ● Record
      </button>
      {rec.state === 'error' && <span className="hint warn">{rec.error}</span>}
    </span>
  );
}

function SceneRow({entry, busy, regenerating, log, onRegenerate, onSaveText, onRecord}) {
  const [draft, setDraft] = useState(entry.effectiveText);
  const [saving, setSaving] = useState(false);
  const logRef = useRef(null);
  const editorRef = useRef(null);

  // Refresh the editor when server state changes (save, regenerate, rebuild),
  // but never while the user has unsaved local edits.
  const dirty = draft.trim() !== entry.effectiveText.trim();
  useEffect(() => {
    if (!dirty) setDraft(entry.effectiveText);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entry.effectiveText]);

  useEffect(() => {
    if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight;
  }, [log]);

  const save = async () => {
    setSaving(true);
    try {
      await onSaveText(entry.sceneId, draft);
    } finally {
      setSaving(false);
    }
  };

  const resetToDefault = async () => {
    setDraft(entry.defaultText);
    setSaving(true);
    try {
      await onSaveText(entry.sceneId, '');
    } finally {
      setSaving(false);
    }
  };

  const insertCue = (cue) => {
    const textarea = editorRef.current;
    const start = textarea?.selectionStart ?? draft.length;
    const next = insertAtSelectionStart(draft, start, cue);
    setDraft(next);
    window.requestAnimationFrame(() => {
      textarea?.focus();
      const cursor = start + cue.length;
      textarea?.setSelectionRange(cursor, cursor);
    });
  };

  const applyPace = (mode) => {
    const textarea = editorRef.current;
    const start = textarea?.selectionStart ?? 0;
    const end = textarea?.selectionEnd ?? 0;
    if (start === end) return;
    const next = paceSelection(draft, start, end, mode);
    setDraft(next);
    window.requestAnimationFrame(() => {
      textarea?.focus();
      textarea?.setSelectionRange(start, start + (next.length - draft.length) + (end - start));
    });
  };

  return (
    <div className={`scene-row ${entry.textMismatch ? 'mismatch' : ''}`}>
      <div className="scene-row-head">
        <span className="mono scene-id">{entry.sceneId}</span>
        <span className="rtl outlet-name">
          {entry.outletName || (entry.segmentType !== 'scene' ? entry.segmentType : '')}
        </span>
        <SourceTag source={entry.source} />
        {entry.isOverridden && <span className="badge badge-attention">edited script</span>}
        {entry.textMismatch && (
          <span className="badge badge-stale" title="The existing WAV was generated from different text than the current script.">
            WAV outdated
          </span>
        )}
        <RegenBadge regen={entry.regen} />
        <span className="scene-row-spacer" />
        <span className="mono duration">{fmt(entry.wavDurationSeconds)}</span>
        {entry.url ? (
          <audio controls preload="none" src={entry.url} />
        ) : (
          <span className="missing">no WAV yet</span>
        )}
        <button
          className="btn"
          disabled={busy || dirty}
          title={dirty ? 'Save the text first' : entry.wavExists ? 'Back up the WAV and regenerate this scene from the current text' : 'Generate this scene from the current text'}
          onClick={() => {
            if (
              window.confirm(
                `${entry.wavExists ? 'Regenerate' : 'Generate'} narration for ${entry.sceneId} from the current script text?` +
                  (entry.wavExists ? '\n\nThe current WAV is backed up, then timings resync and outputs rebuild.' : '')
              )
            ) {
              onRegenerate(entry.sceneId);
            }
          }}
        >
          {regenerating ? 'Working…' : entry.wavExists ? 'Regenerate' : 'Generate scene'}
        </button>
        <RecordControl entry={entry} busy={busy} dirty={dirty} onRecord={onRecord} />
      </div>

      <div className="tts-cue-bar" aria-label="Hamsa text cues">
        {TTS_CUES.map((group) => (
          <div className="tts-cue-group" key={group.group}>
            <span className="tts-cue-label">{group.group}</span>
            {group.items.map((item) => (
              <button key={item.label} type="button" className="btn cue-btn" title={item.title} onClick={() => insertCue(item.value)}>
                {item.label}
              </button>
            ))}
          </div>
        ))}
        <div className="tts-cue-group">
          <span className="tts-cue-label">Selection</span>
          <button
            type="button"
            className="btn cue-btn"
            title="Tightens selected text by removing pause punctuation. Hamsa realtime API does not expose inline speed control."
            onClick={() => applyPace('faster')}
          >
            Faster
          </button>
          <button
            type="button"
            className="btn cue-btn"
            title="Adds heavier pauses to selected text. Hamsa realtime API does not expose inline speed control."
            onClick={() => applyPace('slower')}
          >
            Slower
          </button>
        </div>
      </div>
      <textarea
        ref={editorRef}
        className="rtl script-editor"
        rows={Math.min(8, Math.max(2, Math.ceil(draft.length / 110)))}
        value={draft}
        onChange={(event) => setDraft(event.target.value)}
        spellCheck={false}
      />
      <div className="script-editor-actions">
        <span className="char-count">{draft.trim().length} chars</span>
        {dirty && (
          <>
            <button className="btn primary" disabled={saving || busy} onClick={save}>
              {saving ? 'Saving…' : 'Save text'}
            </button>
            <button className="btn ghost" disabled={saving} onClick={() => setDraft(entry.effectiveText)}>
              Discard
            </button>
          </>
        )}
        {!dirty && entry.isOverridden && (
          <button className="btn ghost" disabled={saving || busy} onClick={resetToDefault}>
            Reset to briefing text
          </button>
        )}
        {dirty && <span className="hint">Unsaved — generating or recording still uses the previous text snapshot.</span>}
        {!dirty && entry.textMismatch && <span className="hint warn">Saved text differs from the WAV — regenerate or re-record to apply.</span>}
      </div>

      {regenerating && log.length > 0 && (
        <pre className="log" ref={logRef}>
          {log.join('\n')}
        </pre>
      )}
    </div>
  );
}

export default function AudioPanel({entries, busy, audioSource, activeSceneId, log, onRegenerate, onSaveText, onRecord, onSetAudioSource}) {
  if (!entries.length) {
    return (
      <section className="audio-panel">
        <h2>Scene narration audio</h2>
        <p className="empty">No narration script yet — build the outputs first (step 6).</p>
      </section>
    );
  }

  const hasAnyWav = entries.some((entry) => entry.wavExists);
  const human = audioSource === 'human';

  return (
    <section className="audio-panel">
      <div className="audio-panel-head">
        <h2>Scene narration audio</h2>
        <div className="audio-source-toggle" role="group" aria-label="Default narration source">
          <span className="hint">Step 7 default:</span>
          <button
            className={`btn ${human ? 'ghost' : 'primary'}`}
            disabled={busy || !human}
            onClick={() => onSetAudioSource('ai')}
            title="Step 7 generates missing scenes with Hamsa AI."
          >
            AI (Hamsa)
          </button>
          <button
            className={`btn ${human ? 'primary' : 'ghost'}`}
            disabled={busy || human}
            onClick={() => onSetAudioSource('human')}
            title="Step 7 only refreshes the manifest (no Hamsa calls) — record each scene yourself."
          >
            Human (record)
          </button>
        </div>
      </div>
      <p className="description">
        This is the exact text read per scene{hasAnyWav ? '' : ' when you run step 7'}. Edit and save any scene before
        generating or recording — edits are stored in <code>audio/text-overrides.json</code> and survive rebuilds. Use{' '}
        <strong>Generate/Regenerate</strong> for Hamsa AI or <strong>Record</strong> to capture your own voice; either
        drops a WAV at the scene path and resyncs timings. In <strong>Human</strong> mode step 7 spends no Hamsa API calls.{' '}
        Text cues use documented Hamsa behaviors: punctuation/paragraphs for pauses, fillers for realism, and supported
        emojis for emotional delivery. Speed and expressiveness sliders are documented in Hamsa Media, but the realtime API
        used here only accepts text, speaker, and dialect; the Faster/Slower buttons therefore reshape selected punctuation
        instead of setting true per-sentence speed.
      </p>
      {entries.map((entry) => (
        <SceneRow
          key={entry.sceneId}
          entry={entry}
          busy={busy}
          regenerating={activeSceneId === entry.sceneId}
          log={activeSceneId === entry.sceneId ? log : []}
          onRegenerate={onRegenerate}
          onSaveText={onSaveText}
          onRecord={onRecord}
        />
      ))}
    </section>
  );
}
