// Default attention-hook variants for the Quote Duel video path. These are
// generic TikTok-style openers (reusable day to day), NOT per-duel content.
// build-briefing-folder injects them into quote-duel.json when the upstream
// file carries no `hooks` of its own, so every day has a stable, selectable set
// (hook-2 is always "بتعرف شو عم بقولو..."). A Codex-authored quote-duel.json may
// override by emitting its own `hooks` array.
export const DEFAULT_DUEL_HOOKS = [
  {id: 'hook-1', text: 'اليوم شو عم بقولوا للبنانية'},
  {id: 'hook-2', text: 'بتعرف شو عم بقولو للشعب اللبناني اليوم؟ مشِّي معي ورح قلك...'},
  {id: 'hook-3', text: 'اسمع اسمع هل الخبرية بالصحف اليوم'}
];

export const DEFAULT_DUEL_OUTRO_AUDIO = {
  id: 'outro',
  file: 'outro.wav',
  text: 'للمزيد من التفاصيل، شاهدوا صفحتنا على يوتيوب. الرابط في الوصف.'
};

// Which hook variant the pipeline uses by default (dashboard + docs). The user
// is testing hook-2 for now; the hook strategy is still open.
export const DEFAULT_HOOK_ID = 'hook-2';

// Normalize a duel doc's hooks: keep its own non-empty `hooks` (or legacy single
// `hook`), otherwise fall back to the defaults. Returns a fresh array.
export const ensureDuelHooks = (quoteDuel) => {
  if (Array.isArray(quoteDuel?.hooks) && quoteDuel.hooks.some((h) => h?.text)) {
    return quoteDuel.hooks
      .filter((h) => h?.text)
      .map((h, i) => ({id: h.id ?? `hook-${i + 1}`, text: h.text}));
  }
  if (quoteDuel?.hook?.text) return [{id: 'hook-1', text: quoteDuel.hook.text}];
  return DEFAULT_DUEL_HOOKS.map((h) => ({...h}));
};

// --- Shared (static, all-dates) hook audio --------------------------------
// Hook WAVs live ONCE under <repo>/audio/hooks/ (not per date) since the hooks
// are static across every date and duel. generate-duel-hooks.mjs synthesizes
// them; the per-date render/mux/split read them from here.

import fs from 'node:fs';
import path from 'node:path';

// <repo>/audio/hooks/ by default; DUEL_HOOKS_DIR overrides it (tests / custom setups).
export const sharedHooksDir = (cwd) =>
  process.env.DUEL_HOOKS_DIR ? path.resolve(process.env.DUEL_HOOKS_DIR) : path.join(cwd, 'audio', 'hooks');
export const sharedHooksManifestPath = (cwd) => path.join(sharedHooksDir(cwd), 'manifest.json');

export const loadSharedHooksManifest = (cwd) => {
  const p = sharedHooksManifestPath(cwd);
  if (!fs.existsSync(p)) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
};

// --hook <id> normalizer: a bare number N → hook-N; falsy/true → null.
export const normalizeHookId = (value) => {
  if (!value || value === true) return null;
  const s = String(value).trim();
  return /^\d+$/.test(s) ? `hook-${s}` : s;
};

/**
 * Resolve the active hook for render/mux/split from the SHARED hooks manifest.
 * @returns {null | {id, text, durationSeconds (buffered), rawSeconds, file, wavPath (absolute)}}
 */
export const resolveSharedHook = (cwd, hookId) => {
  if (!hookId) return null;
  const manifest = loadSharedHooksManifest(cwd);
  const entry = manifest?.hooks?.[hookId];
  if (!entry) return null;
  return {
    id: hookId,
    text: entry.text ?? '',
    durationSeconds: entry.bufferedSeconds ?? entry.durationSeconds ?? 2.5,
    rawSeconds: entry.durationSeconds ?? null,
    file: entry.file ?? `${hookId}.wav`,
    wavPath: path.join(sharedHooksDir(cwd), entry.file ?? `${hookId}.wav`)
  };
};

/**
 * Resolve the shared end-card voice line generated by Step 17.
 * @returns {null | {id, text, durationSeconds (buffered), rawSeconds, file, wavPath (absolute)}}
 */
export const resolveSharedOutro = (cwd) => {
  const manifest = loadSharedHooksManifest(cwd);
  const entry = manifest?.outro;
  if (!entry) return null;
  return {
    id: DEFAULT_DUEL_OUTRO_AUDIO.id,
    text: entry.text ?? DEFAULT_DUEL_OUTRO_AUDIO.text,
    durationSeconds: entry.bufferedSeconds ?? entry.durationSeconds ?? null,
    rawSeconds: entry.durationSeconds ?? null,
    file: entry.file ?? DEFAULT_DUEL_OUTRO_AUDIO.file,
    wavPath: path.join(sharedHooksDir(cwd), entry.file ?? DEFAULT_DUEL_OUTRO_AUDIO.file)
  };
};
